name: RL
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - numpy=1.19.2
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image=0.18.1
  - seaborn=0.11.2
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - nvidia::cudatoolkit=10.2  # uncomment for gpu
  - pip:
      - dm-env
      - termcolor==1.1.0
      - tb-nightly
      - imageio==2.9.0  # need to comment out two lines for m1 macs
      - imageio-ffmpeg==0.4.4
      - hydra-core
      - hydra-submitit-launcher
      - pandas==1.3.0
      - ipdb==0.13.9
      - yapf==0.31.0
      - sklearn==0.0
      - matplotlib==3.4.2
      - wandb
      - opencv-python==4.5.3.56
      - PyOpenGL-accelerate
      - ale-py
      - gym